## Drive and Dependecies


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/MyDrive/cicddos2019/03-11

/content/drive/MyDrive/cicddos2019/03-11


In [ ]:
%ls

7_classes/                     clean_3_without_timestamp.csv    NetBIOS.csv
binary_balanced_dataset.csv    complete_dataset.csv             Portmap.csv
binary_dataset.csv             LDAP.csv                         Syn.csv
clean_1.csv                    MSSQL.csv                        UDP.csv
clean_2_wihtout_timestamp.csv  multiclass_balanced_dataset.csv  UDPLag.csv
clean_2_with_timestamp.csv     multiclass_dataset.csv


In [ ]:
import pandas as pd
from google.colab import files
pd.options.display.max_rows = 99999
pd.set_option('max_colwidth', 400)
#df=pd.read_csv('./clean_1.csv')

## Feature Engineering

In [ ]:
 #%tensorflow_version 2.x
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda, Flatten
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras import callbacks
from keras.callbacks import CSVLogger
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
import numpy as np
np.random.seed(0)

In [ ]:
#loading dataset
import pandas as pd
df = pd.read_csv("./binary_balanced_dataset.csv")
x=df.drop('Label',axis='columns')
y=df.Label
y = pd.DataFrame(y)

#normalizing the data
normalized_df=(x-x.mean())/x.std()
normalized_df=normalized_df.drop(['Flow Bytes/s'], axis=1)
normalized_df=normalized_df.drop([' Flow Packets/s'], axis=1)

#y = pd.get_dummies(y,prefix=['Label'], drop_first=True)

normalized_df.head()

Unnamed: 0   Source IP   Source Port   Destination IP   Destination Port  \
0   -1.732050   -0.108937     -1.311375         0.607237          -0.816892   
1   -1.732049   -0.108937     -1.311335         0.607237           1.385477   
2   -1.732047   -0.108937     -1.320052         0.607237           0.816967   
3   -1.732046   -0.108937     -1.311296         0.607237           1.407635   
4   -1.732045   -0.108937     -1.311257         0.607237           0.816664   

    Protocol  Total Length of Fwd Packets   Fwd Packet Length Max  \
0   0.879782                    -0.136929               -0.041140   
1   0.879782                    -0.095277                0.124671   
2   0.879782                    -0.123045                0.014130   
3   0.879782                    -0.123045                0.014130   
4   0.879782                    -0.123045                0.014130   

    Fwd Packet Length Min   Fwd Packet Length Mean  ...   URG Flag Count  \
0                0.318124                 0.243298  ...        -0.530505   
1                0.581629                 0.508213  ...        -0.530505   
2                0.405959                 0.331603  ...        -0.530505   
3                0.405959                 0.331603  ...        -0.530505   
4                0.405959                 0.331603  ...        -0.530505   

    CWE Flag Count   Average Packet Size   Avg Fwd Segment Size  \
0        -0.327943              0.242815               0.243298   
1        -0.327943              0.514853               0.508213   
2        -0.327943              0.333495               0.331603   
3        -0.327943              0.333495               0.331603   
4        -0.327943              0.333495               0.331603   

    Avg Bwd Segment Size   Subflow Fwd Bytes  Init_Win_bytes_forward  \
0              -0.307632           -0.136877               -0.456437   
1              -0.307632           -0.095224               -0.456437   
2              -0.307632           -0.122993               -0.456437   
3              -0.307632           -0.122993               -0.456437   
4              -0.307632           -0.122993               -0.456437   

    Init_Win_bytes_backward   Idle Std   Inbound  
0                 -0.209956  -0.160312  0.818546  
1                 -0.209956  -0.160312  0.818546  
2                 -0.209956  -0.160312  0.818546  
3                 -0.209956  -0.160312  0.818546  
4                 -0.209956  -0.160312  0.818546  

[5 rows x 36 columns]

In [ ]:
#y = pd.read_csv("/content/drive/My Drive/dos_dataset/y.csv")
#y=y['Label']
y.head()

Label
0      1
1      1
2      1
3      1
4      1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.3, random_state=0)
y_train = np.array(y_train)

y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1]))

print('xtrain={}, ytrain={}, xtest={}, ytest={}'.format(X_train.shape,y_train.shape,X_test.shape,y_test.shape))

xtrain=(1863218, 36), ytrain=(1863218, 1), xtest=(798522, 36), ytest=(798522, 1)


## XGBoost



In [ ]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, y_train)

#import pickle
#pickle.dump(model, open("/content/drive/My Drive/dos_dataset/final_xgb.pickle.dat", "wb"))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_train.shape

(1863218, 1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('XGBoost Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print('Precision = ', metrics.precision_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                 digits=2,
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

XGBoost Classifier
Accuracy =  99.99937384317526
Precision =  100.0
Confusion Matrix =
 [[399120      0]
 [     5 399397]]
Recall = 0.9999937384317527
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    399120
           1       1.00      1.00      1.00    399402

    accuracy                           1.00    798522
   macro avg       1.00      1.00      1.00    798522
weighted avg       1.00      1.00      1.00    798522

F1 Score =  0.9999937384309993


## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Logistic Regression')

print('Accuracy = ', metrics.accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Logistic Regression
Accuracy =  99.94890560310174
Confusion Matrix =
 [[398869    251]
 [   157 399245]]
Recall = 0.9994890560310173
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    399120
           1       1.00      1.00      1.00    399402

    accuracy                           1.00    798522
   macro avg       1.00      1.00      1.00    798522
weighted avg       1.00      1.00      1.00    798522

F1 Score =  0.9994890559177314


## Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Decision Tree Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Decision Tree Classifier
Accuracy =  99.99912338044538
Confusion Matrix =
 [[399119      1]
 [     6 399396]]
Recall = 0.9999912338044538
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    399120
           1       1.00      1.00      1.00    399402

    accuracy                           1.00    798522
   macro avg       1.00      1.00      1.00    798522
weighted avg       1.00      1.00      1.00    798522

F1 Score =  0.9999912338033988
