## Drive and Dependecies


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd /content/drive/MyDrive/cicddos2019/03-11

/content/drive/MyDrive/cicddos2019/03-11


In [ ]:
%ls

7_classes/                     clean_3_without_timestamp.csv    NetBIOS.csv
binary_balanced_dataset.csv    complete_dataset.csv             Portmap.csv
binary_dataset.csv             LDAP.csv                         Syn.csv
clean_1.csv                    MSSQL.csv                        UDP.csv
clean_2_wihtout_timestamp.csv  multiclass_balanced_dataset.csv  UDPLag.csv
clean_2_with_timestamp.csv     multiclass_dataset.csv


In [ ]:
import pandas as pd
from google.colab import files
pd.options.display.max_rows = 99999
pd.set_option('max_colwidth', 400)
#df=pd.read_csv('./clean_1.csv')

## Feature Engineering

In [ ]:
 #%tensorflow_version 2.x
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda, Flatten
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras import callbacks
from keras.callbacks import CSVLogger
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
import numpy as np
np.random.seed(0)

In [ ]:
#loading dataset
import pandas as pd
df = pd.read_csv("./multiclass_balanced_dataset.csv")
x=df.drop('Label',axis='columns')
y=df.Label
y = pd.DataFrame(y)

#normalizing the data
normalized_df=(x-x.mean())/x.std()
normalized_df=normalized_df.drop(['Flow Bytes/s'], axis=1)
normalized_df=normalized_df.drop([' Flow Packets/s'], axis=1)

#y = pd.get_dummies(y,prefix=['Label'], drop_first=True)

normalized_df.head()

Unnamed: 0   Source IP   Source Port   Destination IP   Destination Port  \
0   -1.732050   -0.113675     -1.085338         0.291053          -1.324661   
1   -1.732049   -0.113675     -1.085298         0.291053           1.170338   
2   -1.732048   -0.113675     -1.094200         0.291053           0.526290   
3   -1.732047   -0.113675     -1.085259         0.291053           1.195441   
4   -1.732045   -0.113675     -1.085219         0.291053           0.525947   

    Protocol  Total Length of Fwd Packets   Fwd Packet Length Max  \
0   0.532286                    -0.364214               -0.475718   
1   0.532286                    -0.297183               -0.355788   
2   0.532286                    -0.341870               -0.435742   
3   0.532286                    -0.341870               -0.435742   
4   0.532286                    -0.341870               -0.435742   

    Fwd Packet Length Min   Fwd Packet Length Mean  ...   URG Flag Count  \
0               -0.429556                -0.444479  ...        -0.250551   
1               -0.307654                -0.321843  ...        -0.250551   
2               -0.388922                -0.403601  ...        -0.250551   
3               -0.388922                -0.403601  ...        -0.250551   
4               -0.388922                -0.403601  ...        -0.250551   

    CWE Flag Count   Average Packet Size   Avg Fwd Segment Size  \
0        -0.170677             -0.435933              -0.444479   
1        -0.170677             -0.313250              -0.321843   
2        -0.170677             -0.395038              -0.403601   
3        -0.170677             -0.395038              -0.403601   
4        -0.170677             -0.395038              -0.403601   

    Avg Bwd Segment Size   Subflow Fwd Bytes  Init_Win_bytes_forward  \
0              -0.155984           -0.364184               -0.332582   
1              -0.155984           -0.297153               -0.332582   
2              -0.155984           -0.341841               -0.332582   
3              -0.155984           -0.341841               -0.332582   
4              -0.155984           -0.341841               -0.332582   

    Init_Win_bytes_backward   Idle Std   Inbound  
0                 -0.103805  -0.172275  0.411907  
1                 -0.103805  -0.172275  0.411907  
2                 -0.103805  -0.172275  0.411907  
3                 -0.103805  -0.172275  0.411907  
4                 -0.103805  -0.172275  0.411907  

[5 rows x 36 columns]

In [ ]:
#y = pd.read_csv("/content/drive/My Drive/dos_dataset/y.csv")
#y=y['Label']
y.head()

Label
0      1
1      1
2      1
3      1
4      1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.3, random_state=0)
y_train = np.array(y_train)

y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1]))

print('xtrain={}, ytrain={}, xtest={}, ytest={}'.format(X_train.shape,y_train.shape,X_test.shape,y_test.shape))

xtrain=(2145824, 36), ytrain=(2145824, 1), xtest=(919640, 36), ytest=(919640, 1)


## XGBoost



In [ ]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, y_train)

#import pickle
#pickle.dump(model, open("/content/drive/My Drive/dos_dataset/final_xgb.pickle.dat", "wb"))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_train.shape

(2145824, 1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('XGBoost Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)

print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                 digits=2,
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

XGBoost Classifier
Accuracy =  99.99934757078857
Confusion Matrix =
 [[114685      0      0      0      0      0      0      0]
 [     0 114783      0      0      0      0      0      0]
 [     1      1 115199      0      0      0      0      0]
 [     0      0      0 114832      0      0      0      0]
 [     0      0      0      0 115167      0      0      0]
 [     0      0      0      0      0 114956      1      0]
 [     1      0      0      0      0      0 114916      0]
 [     0      0      0      0      0      1      1 115096]]
Recall = 0.9999934757078857
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    114685
           1       1.00      1.00      1.00    114783
           2       1.00      1.00      1.00    115201
           3       1.00      1.00      1.00    114832
           4       1.00      1.00      1.00    115167
           5       1.00      1.00      1.00    114957
           6       1.00   

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Logistic Regression')

print('Accuracy = ', metrics.accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Logistic Regression
Accuracy =  97.54588752120395
Confusion Matrix =
 [[114074     62      7      0    117    390     28      7]
 [     2 114135      2     17    627      0      0      0]
 [   185      8 114788    107     17     63     21     12]
 [    29    394    374 104609    125     15   9225     61]
 [    99    648     92    328 113701    168     37     94]
 [    15      0     24     19      0 114769      6    124]
 [    13      0      0   3703     43     15 107640   3503]
 [    30      0      0    545    226    361    581 113355]]
Recall = 0.9754588752120394
Classification Report =
               precision    recall  f1-score   support

           0       1.00      0.99      1.00    114685
           1       0.99      0.99      0.99    114783
           2       1.00      1.00      1.00    115201
           3       0.96      0.91      0.93    114832
           4       0.99      0.99      0.99    115167
           5       0.99      1.00      0.99    114957
           6       0.92  

## Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Decision Tree Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Decision Tree Classifier
Accuracy =  99.9936931842895
Confusion Matrix =
 [[114680      0      2      1      1      0      0      1]
 [     4 114774      3      0      2      0      0      0]
 [     2      0 115196      0      3      0      0      0]
 [     0      0      2 114827      2      0      1      0]
 [     2      0      0      2 115159      1      1      2]
 [     1      0      0      2      4 114947      2      1]
 [     1      0      1      2      3      0 114909      1]
 [     0      0      0      1      4      2      1 115090]]
Recall = 0.999936931842895
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    114685
           1       1.00      1.00      1.00    114783
           2       1.00      1.00      1.00    115201
           3       1.00      1.00      1.00    114832
           4       1.00      1.00      1.00    115167
           5       1.00      1.00      1.00    114957
           6       1.0